<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('projects')->insert([
            ['id' => 1,
             'name' => 'Portfolio Website',
             'pretty_url' => 'portfolio-website-v3',
             'short_description' => 'Portfolio V3',
             'long_description' => '',
             'image' => null,
             'text_logo' => 'MB',
             'fa_icon_logo' => null,
             'type' => 'project',
            ],
            ['id' => 2,
             'name' => 'Emotion Detection (Iranian Propaganda)',
             'pretty_url' => 'mres-project-emotion-detection-iranian-propaganda',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => 'fa-search',
             'type' => 'project',
            ],
            ['id' => 3,
             'name' => 'Sentiment Analysis (Iranian Propaganda)',
             'pretty_url' => 'mres-project-sentiment-analysis-iranian-propaganda',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => 'fa-search',
             'type' => 'project',
            ],
            ['id' => 4,
             'name' => 'Grade Calc (V2)',
             'pretty_url' => 'grade-calc-v2',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => 'fa-graduation-cap',
             'type' => 'project',
            ],
            ['id' => 5,
             'name' => 'Device Inventory Manager',
             'pretty_url' => 'device-inventory-manager',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => null,
             'type' => 'project',
            ],
            ['id' => 6,
             'name' => "Freshers Chatbot & FAQ's Website",
             'pretty_url' => 'mcomp-project-chatbot-faqs',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => 'fa-comment-dots',
             'type' => 'project',
            ],
            ['id' => 7,
             'name' => 'Keyword Extractor API',
             'pretty_url' => 'mcomp-project-keyword-extractor-api',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => null,
             'type' => 'project',
            ],
            ['id' => 8,
             'name' => 'Sentiment Analysis - Amazon Reviews',
             'pretty_url' => 'mcomp-sentiment-analysis-amazon-reviews',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => 'fa-search',
             'type' => 'project',
            ],
            ['id' => 9,
             'name' => 'Currency Converter',
             'pretty_url' => 'mcomp-currency-converter',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => 'fa-dollar-sign',
             'type' => 'project',
            ],
            ['id' => 10,
             'name' => 'Automatic sentiment and emotion labelling of Iranian state-sponsored propaganda tweets and ',
             'pretty_url' => '',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => null,
             'type' => 'education',
            ],
            ['id' => 11,
             'name' => 'A chatbot to facilitate new undergraduate Computer Science students’ transition to university: is it technically feasible and would students find it useful?',
             'pretty_url' => '',
             'short_description' => '',
             'long_description' => '',
             'image' => null,
             'text_logo' => null,
             'fa_icon_logo' => null,
             'type' => 'education',
            ],
        ]);
    }
}
