name: Build Assets
on:
  workflow_run:
    workflows: ["Pest"]
    types:
      - completed
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      VITE_PUSHER_APP_KEY: ${{ secrets.PUSHER_KEY }}
      VITE_PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_CLUSTER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Composer install
        run: composer install
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18.12.0'
          check-latest: true
      - name: Install NPM dependencies
        run: npm install
      - name: Compile assets for production
        run: npm run build
      - name: Stage changed files
        run: git add public/build -f
      - name: Commit changes
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -m 'build assets'
      - name: Tag
        run: git tag latest
      - name: Push tag
        run: git push -f --tags
